"""
ML Training Script -- RandomForest on Elevator Simulation Data.

Reads the CSV generated by the simulator (elevator_training_data.csv),
trains a RandomForestRegressor to predict passenger wait_time_sec from
dispatch features, and reports model performance metrics.

Usage:
    python -m backend.ml.train                         # default CSV path
    python -m backend.ml.train data/custom_data.csv    # custom CSV
"""

from __future__ import annotations

import os
import sys
import csv
import joblib
import numpy as np

# Resolve project root
_project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


# ═══════════════════════════════════════════════════════════════════════════
# Feature configuration
# ═══════════════════════════════════════════════════════════════════════════
FEATURE_COLUMNS = [
    "origin_floor",
    "dest_floor",
    "call_priority",          # will be encoded: NORMAL=0, EXPRESS=1
    "assigned_elevator_id",
    "elevator_load_kg_at_pickup",
    "traffic_intensity",
    "hour_of_day",
    "gbfs_score",
    "direction_match",
    "direction_weight",
    "load_weight",
    "distance_weight",
    "wait_weight",
]

TARGET_COLUMN = "wait_time_sec"


# ═══════════════════════════════════════════════════════════════════════════
# Data loading (pure stdlib csv -- no pandas dependency required)
# ═══════════════════════════════════════════════════════════════════════════
def load_csv(csv_path: str) -> tuple[list[str], list[dict]]:
    """Load CSV and return (headers, rows) as list of dicts."""
    with open(csv_path, "r", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        headers = reader.fieldnames or []
        rows = list(reader)
    return headers, rows


def prepare_dataset(rows: list[dict]) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """
    Match assignment rows (which contain feature values) with completion rows
    (which contain the wait_time_sec target) via call_id.
    """
    # 1. Collect wait times from completion rows
    wait_times = {}
    for row in rows:
        wt = row.get(TARGET_COLUMN, "")
        cid = row.get("call_id", "")
        if cid and wt and wt != "None":
            wait_times[cid] = float(wt)

    # 2. Extract features from assignment rows where we have a known wait time
    filtered = []
    for row in rows:
        cid = row.get("call_id", "")
        if not cid or cid not in wait_times:
            continue
        
        # Skip rows with missing feature values
        skip = False
        for col in FEATURE_COLUMNS:
            val = row.get(col, "")
            if val is None or val == "" or val == "None":
                skip = True
                break
        if skip:
            continue

        # We found a valid assignment row for a completed call
        row["_target_wait_time"] = wait_times[cid]
        filtered.append(row)

    if not filtered:
        print("  [ERROR] No valid training rows found in CSV.")
        print("          Run the simulation first to generate data.")
        sys.exit(1)

    # Build arrays
    X_data = []
    y_data = []

    for row in filtered:
        features = []
        for col in FEATURE_COLUMNS:
            val = row[col]
            if col == "call_priority":
                features.append(1.0 if val == "EXPRESS" else 0.0)
            else:
                features.append(float(val))
        X_data.append(features)
        y_data.append(row["_target_wait_time"])

    return np.array(X_data), np.array(y_data), FEATURE_COLUMNS


# ═══════════════════════════════════════════════════════════════════════════
# Training
# ═══════════════════════════════════════════════════════════════════════════
def train_model(
    X: np.ndarray,
    y: np.ndarray,
    feature_names: list[str],
    n_estimators: int = 100,
    max_depth: int = 10,
    random_state: int = 42,
) -> tuple[RandomForestRegressor, dict]:
    """
    Train a RandomForestRegressor and return (model, metrics_dict).
    """
    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=random_state
    )

    print(f"  Training set  : {len(X_train)} samples")
    print(f"  Test set      : {len(X_test)} samples")
    print(f"  Features      : {len(feature_names)}")
    print()

    # Fit
    model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=random_state,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Metrics
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))

    metrics = {
        "r2_score": round(r2, 4),
        "mae": round(mae, 4),
        "rmse": round(rmse, 4),
        "train_samples": len(X_train),
        "test_samples": len(X_test),
        "n_estimators": n_estimators,
        "max_depth": max_depth,
    }

    # Feature importances
    importances = dict(zip(feature_names, model.feature_importances_))
    sorted_imp = sorted(importances.items(), key=lambda x: x[1], reverse=True)

    return model, metrics, sorted_imp


# ═══════════════════════════════════════════════════════════════════════════
# Reporting
# ═══════════════════════════════════════════════════════════════════════════
def print_report(metrics: dict, importances: list[tuple[str, float]]) -> None:
    """Print a formatted training report to stdout."""
    print("=" * 60)
    print("  ML MODEL TRAINING REPORT")
    print("=" * 60)
    print(f"  Model            : RandomForestRegressor")
    print(f"  Estimators       : {metrics['n_estimators']}")
    print(f"  Max Depth        : {metrics['max_depth']}")
    print(f"  Train Samples    : {metrics['train_samples']}")
    print(f"  Test Samples     : {metrics['test_samples']}")
    print("-" * 60)
    print(f"  R2 Score         : {metrics['r2_score']:.4f}")
    print(f"  MAE              : {metrics['mae']:.4f} seconds")
    print(f"  RMSE             : {metrics['rmse']:.4f} seconds")
    print("-" * 60)
    print("  Feature Importances (sorted):")
    for rank, (feat, imp) in enumerate(importances, 1):
        bar = "#" * int(imp * 50)
        print(f"    {rank:>2}. {feat:<30} {imp:.4f}  {bar}")
    print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════
# Entry point
# ═══════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    default_csv = os.path.join(_project_root, "data", "elevator_training_data.csv")
    csv_path = sys.argv[1] if len(sys.argv) > 1 else default_csv

    if not os.path.exists(csv_path):
        print(f"  [ERROR] CSV file not found: {csv_path}")
        print("          Run the simulation first:  python -m backend.main")
        sys.exit(1)

    print()
    print("=" * 60)
    print("  ELEVATOR DISPATCHER -- ML TRAINING PIPELINE")
    print("=" * 60)
    print(f"  CSV Source: {csv_path}")
    print()

    # Load
    print("  Loading data...")
    headers, rows = load_csv(csv_path)
    print(f"  Total CSV rows   : {len(rows)}")
    print(f"  CSV columns      : {len(headers)}")
    print()

    # Prepare
    print("  Preparing features...")
    X, y, feature_names = prepare_dataset(rows)
    print(f"  Valid samples    : {len(X)}")
    print(f"  Target range     : [{y.min():.1f}s, {y.max():.1f}s]")
    print(f"  Target mean      : {y.mean():.2f}s")
    print()

    # Train
    print("  Training RandomForest...")
    model, metrics, importances = train_model(X, y, feature_names)

    # Report
    print_report(metrics, importances)

    # Save model
    model_dir = os.path.join(_project_root, "data")
    os.makedirs(model_dir, exist_ok=True)
    model_path = os.path.join(model_dir, "trained_model.pkl")
    joblib.dump(model, model_path)
    print(f"\n  Model saved to: {model_path}")
    print(f"  Load with:  model = joblib.load('{model_path}')")
    print()
